spring:
  application:
    name: Spring_Bookstore # Nome da aplicação

  datasource:
    url: jdbc:mysql://localhost:3306/SpringBookstore?useSSL=false&serverTimezone=UTC
    username: vitor
    password: sua_senha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou validate / create-drop / none (ajuste conforme ambiente)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Estratégia para compatibilidade com Swagger/Springdoc

# Configuração opcional do Springdoc OpenAPI (Swagger)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
